openapi: 3.0.0
info:
  title: Example API Platform
  version: 1.0.0
  description: Тестовое описание платформы
  contact:
    name: Anton Golomazov
    url: 'https://vk.com/agolomazov'
    email: cesear@bk.ru
  termsOfService: 'https://yourlinktodocument.com'
  license:
    name: unlicense
    url: 'https://linktolicense.com'
servers:
  - url: 'http://localhost:3000'
x-json-schema-faker:
  locale: ru
  min-items: 2
  max-items: 10
  resolve-json-path: true
paths:
  /projects:
    get:
      summary: 'Получение списка проектов, доступных текущему пользователю'
      tags:
        - Проекты
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/projects/ProjectsListResponse.yaml
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: getProjects
      description: Получить список доступных проектов
    post:
      summary: Создание проекта
      operationId: createProject
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/projects/ProjectResponse.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      description: Создание сущности Проект
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/projects/ProjectModel.yaml
        description: Модель проекта
      tags:
        - Проекты
components:
  schemas: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
security:
  - jwt: []
tags:
  - name: Проекты
